language: php
sudo: false

php:
  - 5.6

branches:
  only:
    - master

before_install:
  - composer install --no-interaction

before_script:
  - mysql -e 'create database IF NOT EXISTS `doctrine`;'

script: phpunit --stop-on-failure

notifications:
  mail: p.scheit@ps-webforge.com