version: '3'

services:
  php:
    image: webforgelabs/php-nodejs:php7.3-node8

    working_dir: /app

    volumes:
      - ./:/app

    environment:
      - COMPOSER_HOME=/app/.composer

  mysqldb:
    image: mysql:5.6

    ports:
      - 3314:3306

    environment:
      - MYSQL_ROOT_PASSWORD=somethingsecret
      - MYSQL_PASSWORD=doctrine
      - MYSQL_USER=doctrine
      - MYSQL_DATABASE=doctrine